default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: garedean_development

test:
  <<: *default
  database: garedean_test

production:
  <<: *default
  database: garedean_production
  username: garedean
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
